# Generated by Django 5.0.6 on 2024-05-19 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianManager',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
            ],
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='Guardians',
            fields=[
            ],
            options={
                'verbose_name_plural': ' Students Guardians',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
    ]
