# Generated by Django 5.0.6 on 2024-05-25 23:52

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_alter_student_guardians_id'),
        ('users', '0003_guardianmanager_guardians'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=255)),
                ('Driver', models.OneToOneField(blank=True, limit_choices_to={'role': 'Driver'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Driver_Bus', to='users.profile')),
                ('Staff', models.OneToOneField(blank=True, limit_choices_to={'role': 'Staff'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Staff_Bus', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Guardians_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('From_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_User', to=settings.AUTH_USER_MODEL)),
                ('To_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagecomment', to='transporter.guardians_message')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=10, unique=True)),
                ('booked_to', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Student_seat', to='home.student')),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bus', to='transporter.buses')),
            ],
        ),
        migrations.CreateModel(
            name='Trips_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trips_Type', models.CharField(choices=[('Home_To_School', 'Home_To_School'), ('School_To_Home', 'School_To_Home')], default='Home_To_School', max_length=50)),
                ('Trip_Date', models.DateField(blank=True, null=True)),
                ('Trips_Status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('PENDING', 'PENDING'), ('Not Yet', 'Not Yet')], default='Not Yet', max_length=30)),
                ('Start_Time', models.TimeField(blank=True, null=True)),
                ('End_Time', models.TimeField(blank=True, null=True)),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bus_Trips', to='transporter.buses')),
            ],
            options={
                'unique_together': {('bus_no', 'Trip_Date')},
            },
        ),
        migrations.CreateModel(
            name='Schedule_Home_To_School',
            fields=[
            ],
            options={
                'verbose_name_plural': ' Home_To_School ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transporter.trips_schedule',),
            managers=[
                ('Home_To_School', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_School_To_Home',
            fields=[
            ],
            options={
                'verbose_name_plural': ' School_To_Home ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transporter.trips_schedule',),
            managers=[
                ('School_To_Home', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trips_Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Take_Time', models.TimeField(blank=True, null=True)),
                ('Student_Leave_Time', models.TimeField(blank=True, null=True)),
                ('Student_Bus_Status', models.CharField(blank=True, choices=[('Take_the_bus', 'Take_the_bus'), ('Leave_the_bus', 'Leave_the_bus'), ('Not_Attend', 'Not_Attend')], max_length=50, null=True)),
                ('Seat_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trips_Seat_id', to='transporter.seats')),
                ('Student_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trips_Student_id', to='home.student')),
                ('Trips_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trips_Bus_id', to='transporter.trips_schedule')),
            ],
            options={
                'unique_together': {('Trips_id', 'Seat_Number'), ('Trips_id', 'Student_Name')},
            },
        ),
    ]
