# Generated by Django 5.0.6 on 2024-05-19 02:33

import django.db.models.deletion
import home.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl')], default='boy', max_length=10)),
                ('guardian_numbber', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='966563481855', help_text='EXP : 966563481855', max_length=128, null=True, region=None)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('address2', models.CharField(blank=True, max_length=2000, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.FileField(default='media/Student/avataer/profile_av.jpg', upload_to=home.models.Path_Student_Avatar)),
                ('Guardians_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Students_Guardians', to='users.profile')),
            ],
            options={
                'ordering': ['-address'],
            },
        ),
    ]
