# Generated by Django 5.0.6 on 2024-05-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_student_guardians_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assign_seats',
            field=models.BooleanField(default=False),
        ),
    ]
